name: Set up environment variables

on:
  push:
    branches:
      - master  # Ce qui déclenche l'action sur la branche master

jobs:
  set_up_env:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          cat .env
